import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
        

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Samirs Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider >
          <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </PrimeReactProvider>

  );
}
