import type { Metadata } from "next";
import "./globals.css";
import 'primereact/resources/themes/bootstrap4-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import { PrimeReactProvider } from "primereact/api";
import '../mocks/server';


        
export const metadata: Metadata = {
  title: "Samirs Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative">
      <PrimeReactProvider>
        {children}
      </PrimeReactProvider>
      </body>
    </html>
  );
}
